[package]
description = "CosmWasm integration testing for Injective"
edition     = "2021"
license     = "MIT OR Apache-2.0"
name        = "injective-test-tube"
repository  = "https://github.com/InjectiveLabs/test-tube"
version     = "1.13.2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = [ "injective-core", "test_artifacts" ]

[dependencies]
base64             = "0.21.5"
cosmrs             = { version = "0.15.0", features = [ "cosmwasm", "rpc" ] }
cosmwasm-schema    = { version = "2.1.1" }
cosmwasm-std       = { version = "2.1.0", features = [ "abort", "cosmwasm_1_2", "cosmwasm_1_3", "cosmwasm_1_4", "cosmwasm_2_0", "iterator", "stargate" ] }
hex                = "0.4.2"
injective-cosmwasm = { version = "0.3.0", path = "../../../cw-injective/packages/injective-cosmwasm" }
injective-std      = { version = "1.13.0", path = "../../../cw-injective/packages/injective-std" }
prost              = "0.12.3"
serde              = "1.0.144"
serde_json         = "1.0.85"
test-tube-inj      = { version = "2.0.1" }
thiserror          = "1.0.34"

[build-dependencies]
bindgen = "0.60.1"

[dev-dependencies]
cw1-subkeys   = "1.1.2"
cw1-whitelist = "1.1.2"
rayon         = "1.5.3"
