[package]
description = "CosmWasm integration testing for Injective"
edition     = "2021"
license     = "MIT OR Apache-2.0"
name        = "injective-test-tube"
repository  = "https://github.com/InjectiveLabs/test-tube"
version     = "1.1.7"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = [ "injective-core", "test_artifacts" ]

[dependencies]
base64             = "0.13.0"
cosmrs             = { version = "0.14.0", features = [ "cosmwasm" ] }
cosmwasm-std       = "1.5.0"
hex                = "0.4.2"
injective-cosmwasm = { version = "0.2.18" }
injective-std      = { version = "0.1.5" }
prost              = "0.11.0"
serde              = "1.0.144"
serde_json         = "1.0.85"
test-tube-inj      = { version = "1.1.1" }
thiserror          = "1.0.34"

[build-dependencies]
bindgen = "0.60.1"

[dev-dependencies]
cw1-whitelist = "1.1.2"
cw1-subkeys   = "1.1.2"
rayon         = "1.5.3"
