[package]
description = "library for building integration testing environments for cosmos-sdk chains in Rust"
edition     = "2021"
license     = "MIT OR Apache-2.0"
name        = "test-tube-inj"
repository  = "https://github.com/InjectiveLabs/test-tube"
version     = "1.1.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64           = "0.21.5"
cosmrs           = { version = "0.15.0", features = [ "cosmwasm", "rpc" ] }
cosmwasm-std     = "1.5.0"
prost            = "0.12.3"
serde            = "1.0.144"
serde_json       = "1.0.85"
tendermint-proto = "0.32.0"
thiserror        = "1.0.34"

[dev-dependencies]
cw1-whitelist = "0.15.0"
rayon         = "1.5.3"
