on:
  push:
  pull_request:
    types: [opened]

name: Unit tests + lints

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v2
        with:
          profile: minimal
          toolchain: 1.78.0
          target: wasm32-unknown-unknown
          override: true
          components: llvm-tools-preview

      - name: Run Tests
        uses: actions-rs/cargo@v2
        with:
          command: test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v2
        with:
          profile: minimal
          toolchain: 1.78.0
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v2
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v2
        with:
          command: clippy
          args: --tests -- -D warnings
